### ISSUE TITLE
1.20.1? please?

### ISSUE THREAD

**Issue by DivannKokos** [sidit77/better-mipmaps#2]
hi, i'm doing modpack for my friends (not public)
and this mod will probably be a very good addition, but here's the problem:

modpack is on 1.20.1 as not all mods have updated yet to 1.20.4 
so i've been wondering if it's gonna be a big deal to back-port mod to 1.20.1?

at least it's one major version, not two different, so i hope it's not so time-consuming, as port can be.

**Comment by sidit77** [comment]
A added a 1.20.1 version to modrinth. I hope it works for you.
